name: duescan
publish_to: 'none'
description: DueScan — Solana network token scanner + AI assessment of growth chances
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0
  intl: ^0.20.2
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  # assets:
    # - assets/icons/
    # - assets/screenshots/
